### ISSUE TITLE
KaguraMea Live Record Comment

### ISSUE THREAD

**Issue by dsrkafuu** [kaguramea-record/kaguramea-record.github.io#10]
旧评论区使用，如有疑问与建议请至 [Issues](https://github.com/kaguramea-record/kaguramea-record.github.io/issues/new/choose)

**Comment by ilharp** [comment]
强 DD 强

**Comment by sibogentleman** [comment]
有意思

**Comment by AngelFalse** [comment]
建议增加Danmu2Ass(将弹幕的xml/json文件转换为Ass字幕文件)工具的说明，经过测试这个工具转换完成的字幕文件可以在Potplayer(Windows)/MXplayer(Android)上正常播放。

此工具的仓库网址：

https://archive.codeplex.com/?p=danmu2ass

二进制文件可通过下载codeplex的存档文件(zip)获得。具体位置如下图：

https://s2.ax1x.com/2019/06/15/Vo1u0e.png

注：语法为 danmu2ass "<xml文件地址>" -s。执行后，会自动在xml文件的同个目录下生成同名的字幕文件。"-s"选项让danmu2ass在转换完毕后自动退出，而不是等待“按任意键退出”。

**Comment by AngelFalse** [comment]
虽然不知道为什么此计划最后终止了，但还是非常感谢各位大佬的无私奉献。

**Comment by Dearf233** [comment]
谢谢你们

**Comment by taoning0403** [comment]
学习linux脚本的时候刚好看到了这个，进来学习一下
